import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import 'Models/org.dart';

class New1 extends StatefulWidget {
  const New1({Key? key}) : super(key: key);

  @override
  State<New1> createState() => _New1State();
}

class _New1State extends State<New1> {

  List<Autogenerated> listAutogenerated = [];



  Future<List<Autogenerated>> getb() async {

    var resp = await http.get(Uri.parse('https://www.boredapi.com/api/activity'));
    var data = jsonDecode(resp.body);

    (data["age"] as List).forEach((s) {
      listAutogenerated.add(Autogenerated.fromJson(s));
    });
    return listAutogenerated;
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    getb();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("ListView.builder")),
      body: ListView.builder(
          itemCount: listAutogenerated.length,
          itemBuilder: (BuildContext context, int index) {
            return ListTile(
                leading: const Icon(Icons.list),
                trailing:  Text(
                  listAutogenerated[index].toString(),
                  style: const TextStyle(color: Colors.pinkAccent, fontSize: 15),
                ),
                title: Text(listAutogenerated[index].toString()));
          }),
    );
  }
}

